# This file was generated by GoReleaser. DO NOT EDIT.
cask "seedify" do
  name "seedify"
  desc "Create seed phrases deterministically from SSH keys"
  homepage "https://github.com/complex-gh/seedify"
  version "0.0.1-test2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seedify"

  on_macos do
    on_intel do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_darwin_amd64.tar.gz"
      sha256 "7db0fe22a2067826be7305613c29299dfeea94baa4710c38b0ee71780f5f054b"
    end
    on_arm do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_darwin_arm64.tar.gz"
      sha256 "c0911e6543e57a37394c321900fb1b19d07027e756e0edf0c69ef41571e4508c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_linux_amd64.tar.gz"
      sha256 "78c1fac22cb04572eb821b9b2f9bb1a9e328ab82c0dee8e5f0c0eb6d08308f3c"
    end
    on_arm do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_linux_arm64.tar.gz"
      sha256 "5e35f7d23099c29cc279ecbe1a66dcd8bec753b994ae9c857e9073b1591cd57a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seedify"]
    end
  end

  caveats do
    "seedify is not signed/notarized. On first run, macOS may block it."
    "If you see "seedify is damaged and cannot be opened", run:"
    "  xattr -dr com.apple.quarantine $(which seedify)"
  end

  # No zap stanza required
end
