# This file was generated by GoReleaser. DO NOT EDIT.
cask "seedify" do
  version "0.0.1-test4"

  name "seedify"
  desc "Create seed phrases deterministically from SSH keys"
  homepage "https://github.com/complex-gh/seedify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seedify"

  on_macos do
    on_intel do
      sha256 "32d4dee22e7c3b535ecabea4e4dc1c9891ecacfa8dc3f3ac58190a57a2b992c8"
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f983e6d3cfbf7ccfde3a4965ff67b63a29e55f8d4aee6883b30ae698daedbc0"
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d154efd320e74e6a5ab9774c0e758f985015a987e8ac995281459d1c7e33390a"
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "414c63b31a807aead39a1d77f80b227d9722edc8a18aa197d8389391d89b3346"
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_linux_arm64.tar.gz"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seedify"] if OS.mac?
  end

  caveats <<~EOS
    seedify is not signed/notarized. On first run, macOS may block it.
    If you see 'seedify is damaged and cannot be opened', run:
      xattr -dr com.apple.quarantine $(which seedify)
  EOS

  # No zap stanza required
end
