# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc "Convert SSH keys to BIP-39 seed phrases"
  homepage "https://github.com/complex-gh/seedify"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complex-gh/seedify/releases/download/v1.6.0/seedify_1.6.0_Darwin_x86_64.tar.gz"
      sha256 "ad9ac8af9e5990870e6807c9c98f6c20dd2f45009bced3c3aae90d48b9bdbcec"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complex-gh/seedify/releases/download/v1.6.0/seedify_1.6.0_Darwin_arm64.tar.gz"
      sha256 "6b5b5359f2c150a904f02bac397b177c22b0b4a377c6b90c13d428126c802558"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.6.0/seedify_1.6.0_Linux_x86_64.tar.gz"
      sha256 "edacef9387ac62ea4df2e274db1437b65947c3c8d0221721d57ad7bc7af59d1f"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.6.0/seedify_1.6.0_Linux_armv7.tar.gz"
      sha256 "1873fa5cb810dacd38a920f9357890cab2d3011d5f8830fe4c2f77ea28d64fee"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.6.0/seedify_1.6.0_Linux_arm64.tar.gz"
      sha256 "fa9d1646e59b702ded2334dbf1593e81de648e697e3e68af51325a633d69aa98"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
