# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc "Convert SSH keys to BIP-39 seed phrases"
  homepage "https://github.com/complex-gh/seedify"
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complex-gh/seedify/releases/download/v1.14.0/seedify_1.14.0_Darwin_x86_64.tar.gz"
      sha256 "05964e60ee86eae76acefb0f1cf12a8ac424c856dc51cd16ec6df3cff2893867"

      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complex-gh/seedify/releases/download/v1.14.0/seedify_1.14.0_Darwin_arm64.tar.gz"
      sha256 "52712df83db0dba11552aee634d383cefb5d48836b075dae66b2d9daf7e99737"

      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.14.0/seedify_1.14.0_Linux_x86_64.tar.gz"
      sha256 "e761fd9fbcd3d1094c0492be9269f559f9832b4d99a9d0e0dec96e5bb1668ce7"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.14.0/seedify_1.14.0_Linux_armv7.tar.gz"
      sha256 "d91244935815b973b9b033f8fa4663d916a779681a68ab8911050648a3283df1"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.14.0/seedify_1.14.0_Linux_arm64.tar.gz"
      sha256 "03349a92058e695686e742a2af1aae7bd4960ba974a7918d085750ea97a3dcda"
      define_method(:install) do
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
